language: cpp
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      
before_script:
script: 
  - cd /home/travis/build/pk-otus/05_editor
  - cmake .
  - cmake --build .
  - cmake --build . --target package  
  - doxygen doxyfile
deploy: 
  - provider:     pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    local-dir:    doxygen/html
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script:       
     - curl -T editor-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -upk-otus:$BINTRAY_API_KEY "https://api.bintray.com/content/pk-otus/OTUS/editor/$TRAVIS_BUILD_NUMBER/editor.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1" 
  
